### ISSUE TITLE
AV Detection

### ISSUE THREAD

**Issue by rolfrennemo** [khr0x40sh/MacroShop#12]
I'm using:
Kali 2016.2-vm-amd64
Veil-Evasion | [Version]: 2.28.2

Using Veil-evasion Payload: powershell/meterpreter/rev_https
Run result payload through MacroShop (macro_safe.py) and add to XLS

Expected behavior

Not detected by AV scanners, but 15/35 did
http://NoDistribute.com/result/NTQHwjYJiFkgAq4n6LZRfC72

Am I missing something?

**Comment by khr0x40sh** [comment]
AV Vendors have begun flagging on certain keywords to try and clamp down on macro "viruses".  I know what (most likely) AV is flagging on, but for now, i am leaving the code as is.  I would suggest looking into concatenating strings in VBA for a solution.
