### ISSUE TITLE
Procedure too large

### ISSUE THREAD

**Issue by adamwattis** [khr0x40sh/MacroShop#2]
I tried using the script on a simple .exe file that was about 1.1mb and got the .vb script just fine. However, when I try to run the macro in an Excel document it gives me an error saying that the procedure is too large. I believe that each procedure can't be larger than 64k, which my generated procedure for the string in base64 must be.
Perhaps you could edit the Python script so that it would create a new procedure after every few thousand lines of string, with var2, var3, etc, then add them all to var1 in the end?

**Comment by khr0x40sh** [comment]
Sure, I'll give it a shot.

**Comment by adamwattis** [comment]
Thanks! That would be great so that you can use .exe files that are larger, and so allowing for a wider range of programs. Looking forward to your update!

**Comment by adamwattis** [comment]
Hi,

When will you be able to look over the issue of not being able to add larger .exe files in a macro? It is an extremely useful tool and I would really appreciate if you fixed it!! Thanks for developing the tool!

Thanks!

**Comment by khr0x40sh** [comment]
I'm looking into now.  Just busy with a ton of other things, but hopefully
an update will be done this week

**Comment by khr0x40sh** [comment]
Latest commit should support large(r) files now.  I tested with putty.exe (~550kB), so I think it should theoretically work up to about a GB if I'm not mistaken (1,092,266,666 B), but I wouldn't exceed more than a few MB :-P
