### ISSUE TITLE
Word Macro

### ISSUE THREAD

**Issue by vendforce** [khr0x40sh/MacroShop#4]
## Office version : 2010

Im having trouble using veil with a word doc and macro , veil works everytime in an excel doc but word doc, the powershell will not work ?

Im using option powershell/meterpreter/rev_https in veil and converting with macroshop its works well with an exel doc everytime but just not with a word doc

UPDATE :

I maybe completely wrong but its seem's to be the code that either veil is creating or that macroshop is converting into a macro that word doc wont run it , seems weird since as I said excel doc runs everytime and I get a powershell but when I use a word doc it fails to execute the macro

I tested a simple greeting macro in word doc to test macro in word
`Private Sub Document_Open() 'Greet user. MsgBox "Greetings", vbOKOnly, "Greetings" End Sub`

when I execute the doc file and word opens I get a message box with message "Greetings" so the macro is executing in word doc and its not a word problem , so I've come to the conlusion its the veil/macroshop code is conflicting with word doc's , that being said I can get a powershell after I create the word doc by opening it and select run in the tool bar and execute the macro manually, the macro will not execute from just opening the file it requires it to be run manually after the doc is opened, and thats with security settings set to off in macros

I'll keep trying to get it to work but it looks like it wont work with word doc

**Comment by khr0x40sh** [comment]
Macroshop uses the Sub Workbook_Open() instead of Document_Open(). You may have to substitute Workbook_Open at the top of the code with Document_Open.  I'll look in to maybe writing that as an option here soon.  Also, the veil-framework has included an updated version of this code in veil-evasion (https://github.com/Veil-Framework/Veil-Evasion) , you should check it out.

**Comment by vendforce** [comment]
Yea Thanks I just changed it to AutoOpen
