### ISSUE TITLE
escaping the back slashes "exeinvb"

### ISSUE THREAD

**Issue by jokeeer** [khr0x40sh/MacroShop#8]
python exeinvba.py --exe test.exe --out test.vb [--dest "C:\Users\Public\Documents\test.exe"] Ensure any backslashes are escaped in the dest variable

can someone please explain what does this mean  ? 

i tried but i dont really understand.

i keep getting this message in the command window 

file "mc.py", line 16
    print "[!] Error: The Destination, " + args.dest + " is not escaped properly. Please escape all backslashes and try again."
                                       ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by jokeeer** [comment]
so after reading and checking the code.  i think i have to put \ twice,  

but i still cant get it to  work . the same issue is appearing again.

python mc.py --exe popcorn.exe --out popcorn.vba [--dest "C:\Users\mnb-o\Desktop\popcorn.exe"]
  File "mc.py", line 16
    print "[!] Error: The Destination, " + args.dest + " is not escaped properly. Please escape all backslashes and try again."
                                       ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by khr0x40sh** [comment]
It should read something like:

python exeinvba.py --exe test.exe --out test.vb --dest C:\Users\mmb-o\Desktop\popcorn.exe

It may not handle the hyphen in the user name if it fails after the above

**Comment by cr4nkapotomus** [comment]
Try 

Python exeinvba.py --exe popcorn.exe --out popcorn.vba --dest "C:\Users\mmb-o\Destop\popcorn.exe"

If Krashs doesn't work

**Comment by khr0x40sh** [comment]
Closing as this is not an issue with the program, it is an issue with the README
